### PR TITLE
Add scroll shadow to `#multipage-nav` wrapper for overflowing screens

### PR DESCRIPTION
**Pull request by ramram-mf**
# Description

This PR attempts to mitigate the overflowing wrapping layout of secondary navigation for non mobile screens by adding a scroll shadow feature to the container, which displays a subtle shadow on the sides where overflowing elements are present.

Current state:
image

Fixed state:
image
image

Link to sample test page: https://foundation-s-tp1-175-se-pxywdd.herokuapp.com/en/what-we-fund/
Related PRs/issues: #10858

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-889)

### CODE REVIEW

**Comment by robdivincenzo** [comment]
Thanks @ramram-mf, adding Nancy for a design review as well!

Nancy, what do you think about this treatment of a horizontal scroll in response to #10858?

**Review by robdivincenzo — APPROVED** [review]
Code approved @ramram-mf! Ideally our plan is to move away from using .scss, but we may have to for this element since it's still using it and a full refactor of the element seems out of scope for this issue.

Please hold off on merging until Nancy takes a look. Thanks!

**Comment by nancyt1** [comment]
@robdivincenzo Can this be a white gradient instead? or a lighter grey if white doesn't look right?

**Comment by ramram-mf** [comment]
This would be a lighter shadow variant:
image
image

**Comment by nancyt1** [comment]
@ramram-mf This [page](https://foundation.mozilla.org/en/privacynotincluded/categories/toys-games/) on the category pill buttons has an example of what I mean with the white gradient. Is that solution feasible in this context?

**Comment by robdivincenzo** [comment]
If I'm understanding this a bit better- it sounds like to do the white gradient, we will lose the disappear / reappear gradient effect. But since we prefer the design to be consistent with the rest of the site, so we should continue to mimic the white gradient example that @nancyt1 linked. 

My 2 cents- I'm ok with losing the additional effects to opt for consistency (even though they're really nice!). And I agree with @ramram-mf that we shouldn't pivot to JS.

**Comment by nancyt1** [comment]
@ramram-mf Actually, talking about this further at crit, we were thinking the better solution for now is just stacking the elements into 2 rows like [mozilla festival](https://www.mozillafestival.org/en/highlights/mozfest-house-amsterdam-2023/) has it. This will allow all links to be visible at once and doesn't need anything fancy. Would that work?

**Comment by ramram-mf** [comment]
Ok here is the revised version of the secondary navigation, this time wrapping around overflowing elements following UI style taken from Mozfest navigation.

image

**Review by nancyt1 — APPROVED** [review]

**Pull request merged**
