### PR TITLE
Cookie Banner EOY style updates

### PR DESCRIPTION
**Pull request by ramram-mf**
# Description

This PR implements the design spec created by the design team in different viewports, streamlining the element cohesion between the cookie banner and the page's content.

## Breakpoint >= 1440px
image

## Breakpoint >= 1080px
image

## Breakpoint >= 810px
image

## Breakpoint >= 576px
image

## Breakpoint mobile default
image

Link to sample test page: https://foundation-s-tp1-1411-c-xdl7qp.herokuapp.com/en/
Related PRs/issues: #13018

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-1465)

### CODE REVIEW

**Review by beccaklam — CHANGES_REQUESTED** [review]
Hi Ram! Thank you for working on this. It's looking good, just needs some additional changes:

- [x] Background colour should be #FAFAFA
- [x] Black stroke border should be removed
- [ ] Can we move the 'close' icon to the top right corner? And would it be possible to make the close icon the same as the one we use in the donate banner?
- [ ] When the button group flows underneath the text (breakpoint ~ >810px) can the buttons should be left-aligned?
- [ ] The heading should change to 22px at breakpoint ~ >810px
- [ ] On the mobile/small breakpoint the top padding should change to 20px

Thank you again Ram! The list looks long but just little details 🙈

**Review by beccaklam — CHANGES_REQUESTED** [review]
Hi Ram! This is looking really good! Thank you for implementing all those changes. There are just a few spacing changes and I think this should be good to merge:

- [x] For breakpoints >1080px and >810px there should be side margins of 41px
- [ ] The margin under the buttons on breakpoint >810px should be 20px

**Review by mmmavis — APPROVED** [review]
✨

**Review by beccaklam — APPROVED** [review]
Hi @ramram-mf thank you for making those changes. This looks good to go from my end! ✅

**Pull request merged**
