### PR TITLE
Remove unused and deprecated newsletter_signup block

### PR DESCRIPTION
**Pull request by robdivincenzo**
# Description

This PR removes an unused and deprecated block within the body field of the `MozfestPrimaryPage` model. The signup block was redesigned via an external effort with Torchbox and this previous `newsletter_signup` is no longer needed here. The new `newsletter_signup` already contains the data.

Link to sample test page:
Related PRs/issues: #9679 #11575

# To Test

Review mozfest homepage and verify "Newsletter Signup With Background" block exists as normal.

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [x] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

**Merge Method**
**💡❗Remember to use squash merge when merging non-feature branches into `main`**

### CODE REVIEW

**Review by jhonatan-lopes — COMMENTED** [review]
Thanks @robdivincenzo! Just checking, are there any of those blocks being used on Mozfest pages? I did a quick check on https://foundation.mozilla.org/cms/reports/block-types-report/ and couldn't find anything.

If there aren't any instances of the old `NewsletterSignupBlock`, then I'm happy to proceed. Otherwise, we might need to think about how to migrate that data to the new blocks.

**Comment by robdivincenzo** [comment]
Wow that report is an amazing tool @jhonatan-lopes! Much simpler than what I did 😅

I verified locally via Django shell w/ staging data. I checked that all instances of `newsletter_signup` blocks in `MozfestPrimaryPage` are using `NewsletterSignupWithBackgroundBlock`. I'd gotten more results but reduced for duplicates and translated pages, it's just about the same. And with no cases of `NewsletterSignupBlock`

Odd side note: I had to use a try-except block because there's a case of a block with a string "Mozilla/mozfest-2022" as an id somewhere in the database 🙈

```
from networkapi.mozfest import models

pages = models.MozfestPrimaryPage.objects.all()

for page in pages:
    try:
        for block in page.body:
            if block.block_type == 'newsletter_signup':
                #print(page.title)
                print(block.block.__class__.__name__)
    except (ValueError, TypeError):
        pass
```

I think with both of our verifications, we can safely say there are no cases of `NewsletterSignupBlock`.

**Review by jhonatan-lopes — APPROVED** [review]
Sounds good to me, thanks!

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

PR has already been merged.

**Pull request merged**
