### PR TITLE
updated product submission form link

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description

Link to sample test page:
Related PRs/issues: #11833

Screenshot 2024-02-06 at 8 35 24 AM

This PR updates the "Submit a product" link on the PNI homepage to `https://mozillafoundation.tfaforms.net/34`.

# Steps to test

1. Visit https://foundation-s-11833-upda-iyzfro.herokuapp.com/en/privacynotincluded/?search=wrong
3. Scroll to the bottom of the page and look for the message pictured above
4. Click the "Submit a product here link"
5. If https://mozillafoundation.tfaforms.net/34  is opened in a new tab, testing is complete!

### CODE REVIEW

**Review by kristinashu — APPROVED** [review]
The link looks good, thank you @danielfmiranda!

**Review by jhonatan-lopes — APPROVED** [review]
LGTM :+1:

**Comment by jhonatan-lopes** [comment]
Hey @danielfmiranda, this PR looks good and is within scope, however looking forward it would be great to have a way to make sure that we don't miss the form being broken again. I'm thinking adding a cron job to https://github.com/MozillaFoundation/mofo-cron to check third-party integrations regularly and ping/email if they fail

@mtdenton @abi-mofo @mmmavis tagging you here for visibility

**Comment by danielfmiranda** [comment]
Thanks for the feedback and great suggestion @jhonatan-lopes! I have created https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11846 to capture the work mentioned 👍

**Pull request merged**
