### PR TITLE
Customizing password protected page

### PR DESCRIPTION
**Pull request by mmmavis**
# Description

This PR customizes the password page based on the provided Figma design. I followed [Wagtail doc](https://docs.wagtail.org/en/stable/advanced_topics/privacy.html#setting-up-a-global-password-required-page) for the implementation. 

Link to sample test page: https://foundation-s-13100-tp1--v4m50x.herokuapp.com/en/who-we-are/test-password-protected-page/ (Password: `test`)
Related PRs/issues: #13100

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-1557)

### CODE REVIEW

**Review by nancyt1 — CHANGES_REQUESTED** [review]
Love!!! Seeing it now, can I request we capitalize all the Ps -> "Password Protected Page"?

**Comment by mmmavis** [comment]
PR updated! @nancyt1

**Review by nancyt1 — APPROVED** [review]
Amazing!

**Review by ramram-mf — APPROVED** [review]
LGTM Mavis, thanks!

**Pull request merged**
