### PR TITLE
Update `Spotlight` homepage posts to `Ideas`, including cta link text

### PR DESCRIPTION
**Pull request by ramram-mf**
# Description

This PR updates the homepage `Spotlight` posts, renaming the block to `Ideas` and adding a `CTA Link Text` field, which is displayed on the lower part of the post component.

Current state:
image
image

Updated state:
image
image

# To test

1. Log in to the [preview app CMS](https://foundation-s-tp1-981-ad-tfr9ki.herokuapp.com/cms/login/?next=/cms/) with admin2:admin2 credentials.
2. Browse the [homepage edit page](https://foundation-s-tp1-981-ad-tfr9ki.herokuapp.com/cms/pages/46/edit/). CTA Link Text be the last field input inside the `Ideas` card. Publish.
3. [Homepage](https://foundation-s-tp1-981-ad-tfr9ki.herokuapp.com/en/) should be updated with the `Ideas` header and CTA latest values.

Link to sample test page: https://foundation-s-tp1-981-ad-tfr9ki.herokuapp.com/
Related PRs/issues: #12601

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-1000)

### CODE REVIEW

**Review by nancyt1 — CHANGES_REQUESTED** [review]
1. The current text links don't go to the corresponding page for me. It just reloads the homepage. 
2. Are you able to make the height of the image the same height as the right column, however long it might get? It's ok if it crops further
SCR-20240729-mnjk

**Comment by ramram-mf** [comment]
@robdivincenzo So, I explored changing the `blog` field to a `LinkBlock` streamfield, but that made getting and displaying the author data an inconsistent process, which would not align with the design refresh scope in my opinion. Model and field names are updated, reflecting the new `Ideas` section naming, but the PR is failing the `Wagtail CI` actions workflow, stating some error with some non existing residual file from my migration olympics. Any thoughts on how to force the CI workflow to pull the latest branch state?

**Comment by nancyt1** [comment]
@ramram-mf The text links seem to be missing on mobile, is that intentional?

**Review by robdivincenzo — APPROVED** [review]
Ty for cleaning up the naming and looking into the `LinkBlock` idea, code LGTM! 🚀

**Comment by ramram-mf** [comment]
> @ramram-mf The text links seem to be missing on mobile, is that intentional?

@nancyt1 Updated the mobile layout so it now looks like this:
image

**Review by nancyt1 — APPROVED** [review]

**Pull request merged**
