### PR TITLE
(WIP) FRU - base and landing

### PR DESCRIPTION
**Pull request by mmmavis**
# ⚠️ ⚠️⚠️ WIP ⚠️⚠️⚠️

### CODE REVIEW

**Comment by mmmavis** [comment]
Hi @nancyt1 can you provide design feedback based on [review app](https://donate-foundation-s-10266-1033-r1xd7e.mofostaging.net/en/) please.

Note that currently review app gets destroyed every time I update this PR. If you are unable to access the link, please let me know and I'll paste you a working one. Thanks!

**Comment by nancyt1** [comment]
@mmmavis The small text at the bottom feels too wide for the page. Do you think we could center the form and title within this container? Or perhaps constrain the small text to 3/4 of the page and not span the whole container?

Screenshot 2023-05-05 at 2 38 56 PM

image

Also, can we update the text below the image to 1.25rem and 300 weight but keep 1rem for mobile? Other than that, all breakpoints look good!

**Comment by mmmavis** [comment]
@nancyt1 I made some adjustment. Here's the new review page: https://donate-foundation-s-10266-1033-mymnk3.mofostaging.net/en/

**Comment by nancyt1** [comment]
@mmmavis I think it looks great and good to go! Thanks Mavis!

**Comment by mmmavis** [comment]
I created a new PR (#10598) for this work because this PR is having some weird CI issues.

Closing this one now.

**Pull request closed without merging**
