### PR TITLE
Merge `feature/donate-help-page` into `main`

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description

Related PRs/issues: #11173

**Links to sample test pages:**
- Donate Help Page: https://donate-foundation-s-feature-do-ppb3ea.mofostaging.net/en/help/
- Donate Help Page (CMS): https://foundation.mozilla.org/cms/pages/21586/edit/ (credentials: admin2/admin2)

This PR has been created to merge in the "Donate Help Page" feature branch, the branch includes the following work:

- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11172
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11177
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11173
- https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11178

# Screenshots

image

### CODE REVIEW

**Comment by Miaatmozilla** [comment]
Approved by me. (Donor Care Team :) )

**Comment by kristinashu** [comment]
The page looks great, thank you @danielfmiranda!

**Review by mmmavis — APPROVED** [review]
R+! Awesome work, @danielfmiranda ! Can't wait to see this page live! 🕺🏻 💃🏻 🕺🏻 💃🏻 🕺🏻 💃🏻 🕺🏻 💃🏻 

If we haven't already, could you create a ticket for adding regression tests for this form? Thank you!

**Comment by danielfmiranda** [comment]
Thanks @mmmavis!

No problem, we have created https://github.com/MozillaFoundation/foundation.mozilla.org/issues/11345 to capture the work of adding regression tests for the form.

**Pull request merged**
