### PR TITLE
Removed trailing slash from 'https://basket-dev.allizom.org/'

### PR DESCRIPTION
**Pull request by mmmavis**
**[we are on `main` code freeze, do not merge just yet]**

Related PRs/issues: #11220

### CODE REVIEW

**Comment by mtdenton** [comment]
Good to go! Holding approval until after the PNI merge

**Review by mtdenton — APPROVED** [review]

**Comment by mmmavis** [comment]
@mtdenton, checking to see if this can be merged today :)

**Comment by mtdenton** [comment]
Totally, I plan to push in about an hour or so

**Comment by mtdenton** [comment]
I'd like to revert this just to eliminate it as a cause for memory issues, happy to put this back in soon.

**Pull request merged**
