### PR TITLE
EOY banner front end

### PR DESCRIPTION
**Pull request by danielfmiranda**
Related PRs/issues: #11180

Link to sample test pages:
- [Link to donate banner edit page (credentials: admin2/admin2)](https://foundation-s-11180-dona-qvgxed.herokuapp.com/cms/snippets/donate_banner/donatebanner/edit/1/)
- [Link to review app homepage with active banner](https://foundation-s-11180-dona-qvgxed.mofostaging.net/en/)

# Description

This ticket includes the following updates to the EOY donate banner:
- [x] Text is now white
- [x] Heading is H1 with bolder Semi bold weight (also updated max character count to 60)
- [x] Body is Body Large but Semi bold weight (also updated max character count 200)
- [x] Removed the Cta text field in the CMS
- [x] Close icon is now white
- [x] Updated background to Red #FF4F5E 
- [x] No overlay
- [x] Image scales and crops differently (used figma for reference, but have some questions for design related to keeping the image within the container) 

# Screenshots

**Desktop (XL):**

Screenshot 2023-11-06 at 19-32-11 Mozilla Foundation

**Desktop (L):**

Screenshot 2023-11-06 at 19-33-27 Mozilla Foundation

**Tablet (M):**

image

**Mobile (S/XS):**

image

### CODE REVIEW

**Comment by danielfmiranda** [comment]
Hi @kristinashu!

I have implemented the front end updates for the end of year banner and the design is now ready for review.

I was wondering if you could please take a look whenever you find a free moment and let me know if everything looks OK?

Thanks in advance!

**Comment by kristinashu** [comment]
This looks amazing! It's resizing very nicely. 

A couple minor things:
- [ ] Could you please add some hint text about the max character count? Although the max counts are higher, I'd like to try to keep the text short. Perhaps for Title says "Recommended max character count of 30" and for Subtitle "Recommended max character count of 60" 
- [ ] For the wider break point, would it be possible to left align the text and button with the rest of the left aligned  content on the page? 
Screenshot 2023-11-07 at 7 28 03 AM

**Comment by danielfmiranda** [comment]
Hi @kristinashu thanks for taking a look at this PR!

I have implemented your feedback and this PR is now ready for re-review.

Here are some screenshots of the updates that I have made:

**Updated help text:**
Screenshot 2023-11-07 at 11-20-03 Editing donate banner - Test Banner - Wagtail

**Updated alignment on large screen sizes:**
Screenshot 2023-11-07 at 11-20-19 Mozilla Foundation

**Review by kristinashu — APPROVED** [review]
Perfect, thank you Daniel!

**Review by jhonatan-lopes — APPROVED** [review]
LGTM :+1:

**Pull request merged**
