### PR TITLE
Add default picture to author detail page

### PR DESCRIPTION
**Pull request by jhonatan-lopes**
# Description

Fixes bug where the default profile picture is not shown on authors detail page.

Link to sample test page:
Related PRs/issues: #10736

### CODE REVIEW

**Comment by jhonatan-lopes** [comment]
Authors index page:
image

Author's detail page:
image

@beccaklam I think we need a higher resolution default picture version for the detail page, as the one we have right now is only 100x100 pixels, so it is quite poor quality for big screens.

**Comment by beccaklam** [comment]
@jhonatan-lopes Agreed, I'll take a look and see if I can find the original file today.

**Comment by beccaklam** [comment]
Hi @jhonatan-lopes I found the original file. I've exported the SVG at a larger size, let me know if this is big enough? (It looks pixelated below but perhaps it will work for the size on RCC).
author-fallback-image

**Comment by jhonatan-lopes** [comment]
Thanks for sending this through @beccaklam! Here's how it looks now:
image

**Review by danielfmiranda — APPROVED** [review]
Looks great! LGTM!

**Pull request merged**
