### PR TITLE
Main navigation dropdown

### PR DESCRIPTION
**Pull request by jhonatan-lopes**
# Description

- #11978
- https://mozilla-hub.atlassian.net/browse/TP-264

**Merge Method**
**💡❗Remember to use regular merge for merging this feature branch into `main`**

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/TP1-29)

### CODE REVIEW

**Comment by sabrinang** [comment]
Great progress on this @jhonatan-lopes! I know you mentioned some things missing but I included some in my review anyway and will leave QA feedback here:

**All**
- _Iconography:_ currently using ascii arrows but can use svg arrow icons in button and links and when icons are used (like in featured section) they are squished and cropped but they can shrink proportionally instead
- _Text style:_ link items are more bold than designed
- _Text alignment:_ link items can align with column headings so that on hover state the highlighted box extends so text is in alignment instead of the box edge
- _Orientation:_ no line indicated when on current page

**Desktop**
- _Dropdown width:_ is there the possibly of extending width/padding beyond container/grid so there is more horizontal space on desktop (see designs) and this could help extend the column width, so the line length isn’t as short
- _Visual detail:_ dropdown menu top border grey is a bit thicker than design

**Tablet**
- _Content alignment:_ width of content can have more left/right margins to match with nav above
- _Spacing:_ Increase spacing above newsletter button

**Tablet/Mobile**
- _Hover state:_ Primary nav item hover states appear beyond row
- _Open/Closed states:_ one accordion open at a time (close previously opened ones)

**CMS Editing Experience**
- _Icons for CMS section:_ will these be updated with the ones I exported for you?
- _Navigation button:_ we can add some help text mentioning if overview column is present this buttons appears in that column
- The spacing of the + signs are very close to the title but it actually aligns with the previous section above it which may be a bit confusing due to the proximity
- If we have multiple navigations made, how do you toggle between them?

**Comment by nancyt1** [comment]
Supplementing Sabrina's comment with screenshots:

- Missing about 1.5rem of space after the last column on mobile before the divider line. Screenshot 2024-04-19 at 7 36 31 PM
- Are we able to add more spacing at these lines? It gets confusing what plus sign belongs to which section. SCR-20240419-ommk
- Nav item should be aligned with the column title. And Is it possible to extend the nav past the mozilla logo and/or decrease margins between the nav columns? Line length does feel a little short.
SCR-20240419-okqs

**Comment by jhonatan-lopes** [comment]
Hi @nancyt1 and @sabrinang, thanks for the feedback!

Some points:

> Iconography: currently using ascii arrows but can use svg arrow icons in button and links and when icons are used (like in featured section) they are squished and cropped but they can shrink proportionally instead

I've set up the backend/templates to use SVGs with a width/height of 18px (font size). Non-vector images will get blurry. There is a ticket to put validation in place so that editors only use SVGs on those image choosers but please let me know if you'd like to remove that restriction to also have raster images.

> Orientation: no line indicated when on current page

This will be handled in a subsequent ticket.

> Dropdown width: is there the possibly of extending width/padding beyond container/grid so there is more horizontal space on desktop (see designs) and this could help extend the column width, so the line length isn’t as short

It's using the `container` class now, but I'll add some negative margins to make it larger.

> Visual detail: dropdown menu top border grey is a bit thicker than design

It's using 1px, exactly as the design indicated. The difference might be that there's 1px from the dropdown's top border + 1px for the navbar's bottom border. I'll try to disable the dropdown's top border on hover and see if that helps.

> Open/Closed states: one accordion open at a time (close previously opened ones)

I'll fix it :+1: 

> Icons for CMS section: will these be updated with the ones I exported for you?

Yes, I'll update those!

> Navigation button: we can add some help text mentioning if overview column is present this buttons appears in that column

Will do

> The spacing of the + signs are very close to the title but it actually aligns with the previous section above it which may be a bit confusing due to the proximity

Yes, this is an issue with Wagtail itself and how it's rendering the form. I'll try to add some CSS overrides from our side...

> If we have multiple navigations made, how do you toggle between them?

You can keep multiple snippets under the "Navigation Menus" menu. To activate one of them, go to "Settings" > "Navigation Menu" and then select the one that you want to activate. Once you click save that menu will be active for the site defined in the setting.


> Missing about 1.5rem of space after the last column on mobile before the divider line. 

Thanks for flagging that up!


> Are we able to add more spacing at these lines? It gets confusing what plus sign belongs to which section. 

Same thing I've flagged before, it's a Wagtail issue with the form but I'll try to put some overrides on our side.

> Nav item should be aligned with the column title. And Is it possible to extend the nav past the mozilla logo and/or decrease margins between the nav columns? Line length does feel a little short.

Will do

**Comment by nancyt1** [comment]
@jhonatan-lopes Is there a way we can add a super small delay on the menu so it doesn't open immediately on mouse over? I'm thinking about the instances where I'm moving my mouse to something past the menu and I don't really want it to flash open. The [wirecutter site](https://www.nytimes.com/wirecutter/) does kinda what i was thinking. I also don't want to lose the snappiness of going between menus tho. 

https://github.com/MozillaFoundation/foundation.mozilla.org/assets/74557207/7879f25d-98be-46fe-b517-5b50d30dafe8

**Comment by jhonatan-lopes** [comment]
Hi @nancyt1, I'll add that to the "animations" ticket!

**Comment by nancyt1** [comment]
Requesting some spacing updates to mobile! The red line is where the nav links should line up too. Hope this is better than me just typing it out.

SCR-20240426-lrua

**Comment by jhonatan-lopes** [comment]
Further feedback has been addressed on #12259

**Review by mmmavis — APPROVED** [review]

**Comment by data-sync-user** [comment]
➤ Kristina Shu commented:

Simon Acosta Torres I can’t tell what this ticket is, is it for dev? Can it be closed?

**Comment by data-sync-user** [comment]
➤ Simon Acosta Torres commented:

Kristina Shu This is a PR that as I can see, has already been merged to the code. I will proceed to close this synced ticket.

**Pull request merged**
