### PR TITLE
Library BaseAuthorsIndexPage

### PR DESCRIPTION
**Pull request by jhonatan-lopes**
# Description

Refactor RCC and Research Hub to have a base authors index page implementation.

Link to sample test page:
Related PRs/issues:

Covers the authors index pages aspects on these:

https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10697
https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10421
https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10420
# Checklist

**Tests**
- [ ] Is the code I'm adding covered by tests?

**Changes in Models:**
- [ ] Did I update or add new fake data?
- [ ] Did I squash my migration?
- [ ] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- [ ] Is my code documented?
- [ ] Did I update the READMEs or wagtail documentation?

### CODE REVIEW

**Review by danielfmiranda — CHANGES_REQUESTED** [review]
Thanks for this work @jhonatan-lopes after testing this out and taking a look at the code, everything is looking good to me regarding the Authors Index Page! 

I did notice in the visual regression test and on my local machine that the Landing Page does not seem to be rendering its banner image:

Screenshot 2023-06-22 at 12-09-35 Build #14791 - Mozilla Foundation - Percy Visual testing as a service


I was wondering if this was already known, and if not, would it be possible to toss in the fix here or on another PR? 

Let me know which you prefer and I would be happy to then approve 👍 thanks!

**Comment by jhonatan-lopes** [comment]
Nice catch @danielfmiranda! Thanks for that, I've pushed a fix now!

**Comment by jhonatan-lopes** [comment]
Fixed on the review app:
image

**Review by danielfmiranda — APPROVED** [review]
Looks great! Thanks @jhonatan-lopes, approved 👍

**Pull request merged**
