### PR TITLE
Responsible Computing Challenge Playbook Pages

### PR DESCRIPTION
**Pull request by jhonatan-lopes**
# Description

Merge RCC feature branch into main. Review design specs and acceptance criteria (#10783)

Link to sample test page:
Related PRs/issues: 
#10424
#10425 
#10426 
#10427 
#10441 
#10428 
#10429 
#10431 
#10432 
#10433 
#10434 
#10435 
#10436 
#10437 
#10466 
#10438 
#10439 
#10697 
#10736 

# Checklist

:warning: **Make sure to check that this PR satisfies the Acceptance Criteria inside each ticket listed above!** :warning: 

**Tests**
- [X] Is the code I'm adding covered by tests?

**Changes in Models:**
- [X] Did I update or add new fake data?
- ~~[ ] Did I squash my migration?~~ (Decided to keep separate migrations for readability)
- [X] Are my changes [backward-compatible](https://github.com/mozilla/foundation.mozilla.org/blob/main/docs/workflow.md#django-migrations-what-to-do-when-working-on-backward-incompatible-migrations). If not, did I schedule a deploy with the rest of the team?

**Documentation:**
- ~~[ ] Is my code documented?~~
- ~~[ ] Did I update the READMEs or wagtail documentation?~~

### CODE REVIEW

**Review by beccaklam — COMMENTED** [review]
The RCC MVP is looking so great @jhonatan-lopes @danielfmiranda! Thank you for your hard work on this :fire: I’ve gone through all the ACs in the PR list. Most of them are good except:

- #[10438](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10438)
- Need to double check the search term in #[10433](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10433)
- Names not alphabetical in #[10434](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10434)
- Some funky button styling in #[10466](https://github.com/MozillaFoundation/foundation.mozilla.org/issues/10466) (though not really a bug we may need to address right now?)

I may have forgotten other things that need addressing but I’ve made comments in all the tickets so if I did miss something you should have still gotten a notification in your email! I will check more for how the pages are matching the designs tomorrow, esp for different device sizes.

Thank you again for your great work on this!

**Comment by beccaklam** [comment]
@jhonatan-lopes Pages/different device sizes are matching the design. Aside from the changes mentioned in my last comment I think this PR is good to merge! @danielfmiranda also mentioned you may already have some tickets ready that address the problems mentioned above?

**Comment by beccaklam** [comment]
@jhonatan-lopes Adding a note here that Joycelyn requested if we could make this the order for the Curriculum Library Filters:

- Topics
- Curricular Area
- Content Types
- Contributors

**Review by danielfmiranda — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
