### PR TITLE
updated margin below DonateLandingPage featured image

### PR DESCRIPTION
**Pull request by danielfmiranda**
# Description

Link to sample test page: https://foundation-s-feature-10-lyr5pm.herokuapp.com/en/donate/
Related PRs/issues: #10364

This PR updates the margin below the Donate Landing Page's "featured image" to `tw-mb-12`.

Per request of design, this update:
- Renders a space of `32px` between the featured image and page title on mobile
- Renders a space of `24px` between the featured image and the page intro on tablet 
- Renders a space of `16px` between the featured image and the page intro on tablet 

# Screenshots:

### Before:

**Mobile Spacing (Note the gap of ~24px):** 
Screenshot 2024-01-09 at 4 52 37 PM

**Desktop Spacing (Note the gap of ~16px):** 
Screenshot 2024-01-09 at 4 57 20 PM

### After:
**Mobile Spacing (Note the updated gap of ~32px):** 

Screenshot 2024-01-10 at 5 15 19 PM

**Tablet Spacing (Note the updated gap of ~24px):** 
Screenshot 2024-01-10 at 5 15 03 PM

**Desktop Spacing (Note the updated gap of ~16px):** 

Screenshot 2024-01-10 at 5 14 45 PM

### CODE REVIEW

**Comment by mmmavis** [comment]
Hi @danielfmiranda , from the code and the rendered page, it seems like on both mobile and desktop, the margin is 24px. Maybe I'm looking at the wrong place?

image

**Review by nancyt1 — APPROVED** [review]
Looks good to me! Thanks!

**Comment by danielfmiranda** [comment]
Thanks for the catch @mmmavis! After taking a look, I found that I have actually gotten the spacing confused. According to the mockups that Nancy linked in #10364, the spacing should be:
- 16px desktop
- 24px tablet
- 32px mobile

I have updated the image with the following classes `tw-mb-16 medium:tw-mb-12 large:tw-mb-8` and have tagged @nancyt1  for a quick re-review

**Review by nancyt1 — APPROVED** [review]
Looks good! Thanks Daniel!

**Review by mmmavis — APPROVED** [review]
🎉

**Pull request merged**
