### PR TITLE
(**DO NOT MERGE YET**) [Petition Field Changes ] Part 2 - Remove references to Petition's old comment_requirements field

### PR DESCRIPTION
**Pull request by mmmavis**
❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗
# ❗ DO NOT MERGE YET.
❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗❗

This is PR for part 2 of the work and should NOT be merged before Part 1 PR.

~⚠️ **It is based off of the [Part 1 PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10961). We'll need to update it to `main` once Part 1 PR is merged in.**~ DONE

# Description

Removed references to Petition's old `comment_requirements` field.

Link to sample test page:
Related PRs/issues: #10659

@jhonatan-lopes Please let me know if I should write any tests. Thanks!

### CODE REVIEW

**Review by jhonatan-lopes — CHANGES_REQUESTED** [review]
Hi Mavis, I think we missed this `TranslatableField` tag: https://github.com/MozillaFoundation/foundation.mozilla.org/blob/main/network-api/networkapi/wagtailpages/pagemodels/campaigns.py#L261

Could you please remove it as well?

**Comment by mmmavis** [comment]
@jhonatan-lopes I included that work in [Part 3 PR](https://github.com/MozillaFoundation/foundation.mozilla.org/pull/10963/files#diff-62de065a3de1e8fe56917af0194a4239e0575943f3b8ecac0235a496db99eb2c). Should I move the code changes here instead?

**Comment by jhonatan-lopes** [comment]
If you could, please. I think that would be better. This way we will be removing all of the references to the old field on this PR, leaving the next PR to just delete the old field.

**Comment by jhonatan-lopes** [comment]
I see, thanks for pointing that out. I think it's OK to leave it there then

**Comment by jhonatan-lopes** [comment]
Superseded by #11062

**Pull request closed without merging**
