### PR TITLE
Fix bug in the new newsletter HOC component

### PR DESCRIPTION
**Pull request by mmmavis**
To fix a bug that's found on the `2023-eoy` feature branch (https://github.com/MozillaFoundation/foundation.mozilla.org/pull/11593)

Make sure the new newsletter HOC component calls `this.props.whenLoaded()` after the component gets mounted so the `Promise` on line 26 of `source/js/common/inject-react/newsletter-signup-module.js` gets resolved.

I've also created a separate ticket for adding Playwright tests for mobile navs.

# Description

Link to sample test page: https://foundation-s-11604-pni--srgt0h.herokuapp.com/en/privacynotincluded/
Related PRs/issues: #11604

### CODE REVIEW

**Comment by tbrlpld** [comment]
Hey @mmmavis. I won't have time on the project anymore. I am assigning the review over to @jhonatan-lopes.

**Comment by jhonatan-lopes** [comment]
Hey @mmmavis, the bug ticket linked seems to be fixed (PNI mobile category nav not working), but I'm not sure if that's what is being addressed here. Can I get a bit more context, please?

**Comment by mmmavis** [comment]
Hey @jhonatan-lopes , sorry for the confusion.

The bug is only seen on the `2023-eoy` branch as one of my newsletter PRs introduced the issue. To see the bug, try clicking on the category nav (on mobile) on this ["2023-eoy" branch review app](https://foundation-s-2023-eoy-qre47u4t.herokuapp.com/en/privacynotincluded/). (The click does nothing). This PR fixes the bug by making sure `this.props.whenLoaded()` gets called.

**Review by jhonatan-lopes — APPROVED** [review]
LGTM thanks @mmmavis

**Pull request merged**
