### PR TITLE
OneTrust Cookie Banner

### PR DESCRIPTION
**Pull request by robdivincenzo**
# Description

This PR introduces the One Trust cookie banner.

Link to sample test page: https://foundation-s-onetrust-d-snyhuf.herokuapp.com/en/
Related PRs/issues: TP1-990 #12657

# To Test

1) Visit the review app
2) There should be a new cookie banner on the bottom

# Launch notes

1) We will need to update the CSP script-src to include `https://cdn.cookielaw.org`. Note: removing this url is also a quick way to block it if things aren't working as expected
2) We will need to verify that the production script is loading correctly. When you view the page source, you should see `data-domain-script="0190e65a-dbec-7548-89af-4b67155ee70a"` on production, but `data-domain-script="0190e65a-dbec-7548-89af-4b67155ee70a-test"` on every other environment

┆Issue is synchronized with this [Jira Story](https://mozilla-hub.atlassian.net/browse/TP1-1144)

### CODE REVIEW

**Review by danielfmiranda — APPROVED** [review]
Hi @robdivincenzo!

Thanks for providing a review app to test this out with. After taking a look at the review app and also at the code, everything is looking good to me. Approved!

**Review by sabrinang — CHANGES_REQUESTED** [review]
- If the scroll bar isn't present, can we make the vertical white strip on the side be hidden too?

image

- If possible, can we make mobile layout breakpoint wider so that we don't get this configuration _(use layout where buttons are stacked aligned center)_:

image

- Check that we are using brand colours where possible (_"Always Active" in another blue, some UI switches and close X in other greys etc.)_

**Comment by robdivincenzo** [comment]
Thanks @sabrinang! The latest feedback is now live and ready for review on the review app:

- Vertical bar now hidden until scroll needed
- Mobile layout breakpoint is now wider to eliminate that configuration
- "Always Active" text is now in brand blue, UI switches and "X" icons are now in brand grey

**Review by sabrinang — APPROVED** [review]
Thanks for applying the changes Rob!

**Pull request merged**
