### PR TITLE
Localize extra form assembly template strings

### PR DESCRIPTION
**Pull request by TheoChevalier**
Related issue: #10694

Heya @mmmavis, any chance we can get these few extra strings localized, or is this adding too much noise to the base template? (I’m following the effort only from afar)

I think we would need at least the checkbox labels (newsletter + privacy policy).
The `title=""` attributes appear when hovering over the fields, and (I think) are read by screen readers as well

Thank you!

### CODE REVIEW

**Comment by mmmavis** [comment]
Hey @TheoChevalier thanks for filing this PR. I was on OOO so didn't spot this PR until yesterday. I'll review it tomorrow as it's close to EOD for me.

**Comment by mmmavis** [comment]
Hi @TheoChevalier , 

Some updates -

We'll need to hold off on this PR for a little bit. We are in the QA process and some issues have been found. It would be better if we don't make more code changes at least until we are done with QA.

**Comment by TheoChevalier** [comment]
Hi @mmmavis, now that FA is live on production, I was wondering when we could plan to launch this?

Thanks!

**Comment by TheoChevalier** [comment]
Thanks @mmmavis, changes look good!

**Review by mmmavis — APPROVED** [review]

**Pull request merged**
